### ISSUE TITLE
Just applying the variable find that returns this module results in the error that find is not a function

### ISSUE THREAD

**Issue by jhony2488** [zerico007/object-array-filter#1]
Just applying the variable find that returns this module results in the error that find is not a function

<img width="832" alt="Captura de Tela 2021-06-29 às 14 40 42" src="https://user-images.githubusercontent.com/52162636/123843179-fdadc180-d8e7-11eb-9593-da87f3ce1500.png">

Because when I checked the type that is returned in find , find returns the object type not the function type, but inside that object the function itself is inside a key in the object called "default".

<img width="626" alt="Captura de Tela 2021-06-29 às 14 44 22" src="https://user-images.githubusercontent.com/52162636/123843625-8167ae00-d8e8-11eb-8c31-75447f612da4.png">

so I applied the function like this:

`find.default({ size }, testArray)`

And it worked, I was able to find and fix the error, but other people might not understand the real error, so please modify the usage examples in this module's documentation to:

![carbon](https://user-images.githubusercontent.com/52162636/123844820-de179880-d8e9-11eb-9b77-5ddc9810338b.png)

**Comment by zerico007** [comment]
Hey. Not sure why you would have that error but I have used this package in my own projects and I've never had to do that. I'll check it out though. Thanks.

**Comment by zerico007** [comment]
Seems you're right. You can only use find by itself if using typescript. thanks again
